### ISSUE TITLE
Final Deliverables Checklist

### ISSUE THREAD

**Issue by enescakir** [bounswe/bounswe2017group11#240]
## Github Repository - Online
- [X] 1.1 Wiki pages that describe your project, research, meetings, and other artifacts
- [X] 1.2 Requirements
- [X] 1.3 All software design documents
- [X] 1.4 User scenarios and mockups
- [x] 1.5 User test cases and testing results (including at least 5 non-member test results) -- scanned
- [X] 1.6 Issues
- [x] 1.7 All code (documented, and with unit tests)
- [x] 1.8 Database dump and script for restoring it on a database.
- [x] 1.9 Manuals (user, system)  -- user manual instructs how users can use the system, system manual describes the system requirements and installation.

### Software:
- [x] 2.1 Final version of code, documented and including unit tests
- [x] 2.2 Packaged Django app
- [x] 2.3 Built React app
- [x] 2.4 .apk file containing the Android solution
- [x] 2.5 "README" file that contains instructions on how to deploy and configure your web and Android applications
- [x] 2.6 Database dump & configuration file used by code to obtain database path / username / password 
- [X] 2.7 Generated real or realistic content (at least 100 items) to jumpstart crowdsourcing & recommendation system
- [x] 2.8 Software documentation (generated as html)
- [x] 2.9 User test cases and testing results (including at least 5 non-member test results) -- scanned
- [X] 2.10 Final presentation (ppt, pptx, pdf)
- [X] 2.11 Project video
- [X] 2.12 Project Plan
- [X] 2.13 Milestone reports (1st and 2nd)
- [x] 2.14 Final Report
 
## Final Report - HARD COPY
- [x] 3.1 Final project assessment (Final Milestone -- assesses the whole process such as lessons learned)
- [x] 3.2 A summary of coding work done by each team member (In tabular format)
- [x] 3.3 Requirements
- [x] 3.4 All design documents
- [x] 3.5 User & system manuals
- [x] 3.6 Project Plan (simplified version in a report-friendly format)

**Comment by GirayEryilmaz** [comment]
This list is a great idea man :+1:  . Perhaps some of the items can be divided into 3 as android, backend and frontend. For example : documentation.

**Comment by halilkalkan** [comment]
Project video is ready. >> https://www.youtube.com/watch?v=S3JcapFK2u0&feature=youtu.be
